config/routes.rb
Tygerfaux::Application.routes.draw do
  resources :residents

  resources :facilities do
    resources :residents
  end

  root :to => 'facilities#index'

end

app/models/facility.rb
class Facility < ActiveRecord::Base
  attr_accessible :name

  has_many :residents
end

app/models/person.rb
class Person
  include Mongoid::Document

end

app/models/resident.rb
class Resident < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :pin, :status

  belongs_to :facility
  validates :pin, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  # GET /facilities
  # GET /facilities.json
  def index
    @facilities = Facility.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @facilities }
    end
  end

  # GET /facilities/1
  # GET /facilities/1.json
  def show
    @facility = Facility.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @facility }
    end
  end

  # GET /facilities/new
  # GET /facilities/new.json
  def new
    @facility = Facility.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @facility }
    end
  end

  # GET /facilities/1/edit
  def edit
    @facility = Facility.find(params[:id])
  end

  # POST /facilities
  # POST /facilities.json
  def create
    @facility = Facility.new(params[:facility])

    respond_to do |format|
      if @facility.save
        format.html { redirect_to @facility, :notice => 'Facility was successfully created.' }
        format.json { render :json => @facility, :status => :created, :location => @facility }
      else
        format.html { render :action => "new" }
        format.json { render :json => @facility.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /facilities/1
  # PUT /facilities/1.json
  def update
    @facility = Facility.find(params[:id])

    respond_to do |format|
      if @facility.update_attributes(params[:facility])
        format.html { redirect_to @facility, :notice => 'Facility was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @facility.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /facilities/1
  # DELETE /facilities/1.json
  def destroy
    @facility = Facility.find(params[:id])
    @facility.destroy

    respond_to do |format|
      format.html { redirect_to facilities_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/residents_controller.rb
class ResidentsController < ApplicationController
  # GET /residents
  # GET /residents.json
  def index
    if params[:facility_id]
      @residents = Resident.find_all_by_facility_id(params[:facility_id]) 
    else
      @residents = Resident.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @residents }
    end
  end

  # GET /residents/1
  # GET /residents/1.json
  def show
    @resident = Resident.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @resident }
    end
  end

  # GET /residents/new
  # GET /residents/new.json
  def new
    @resident = Resident.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @resident }
    end
  end

  # GET /residents/1/edit
  def edit
    @resident = Resident.find(params[:id])
  end

  # POST /residents
  # POST /residents.json
  def create
    @resident = Resident.new(params[:resident])

    respond_to do |format|
      if @resident.save
        format.html { redirect_to @resident, :notice => 'Resident was successfully created.' }
        format.json { render :json => @resident, :status => :created, :location => @resident }
      else
        format.html { render :action => "new" }
        format.json { render :json => @resident.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /residents/1
  # PUT /residents/1.json
  def update
    @resident = Resident.find(params[:id])

    respond_to do |format|
      if @resident.update_attributes(params[:resident])
        format.html { redirect_to @resident, :notice => 'Resident was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @resident.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /residents/1
  # DELETE /residents/1.json
  def destroy
    @resident = Resident.find(params[:id])
    @resident.destroy

    respond_to do |format|
      format.html { redirect_to residents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/helpers/residents_helper.rb
module ResidentsHelper
end

app/views/facilities/_form.html.erb
<%= form_for(@facility) do |f| %>
  <% if @facility.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@facility.errors.count, "error") %> prohibited this facility from being saved:</h2>

      <ul>
      <% @facility.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facilities/edit.html.erb
<h1>Editing facility</h1>

<%= render 'form' %>

<%= link_to 'Show', @facility %> |
<%= link_to 'Back', facilities_path %>

app/views/facilities/index.html.erb
<h1>Listing facilities</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @facilities.each do |facility| %>
  <tr>
    <td><%= facility.name %></td>
    <td><%= link_to 'Show', facility %></td>
    <td><%= link_to 'Edit', edit_facility_path(facility) %></td>
    <td><%= link_to 'Destroy', facility, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
    <td><%= link_to 'Residents', facility_residents_path(facility) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Facility', new_facility_path %>

app/views/facilities/new.html.erb
<h1>New facility</h1>

<%= render 'form' %>

<%= link_to 'Back', facilities_path %>

app/views/facilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @facility.name %>
</p>


<%= link_to 'Edit', edit_facility_path(@facility) %> |
<%= link_to 'Back', facilities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tygerfaux</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/residents/_form.html.erb
<%= form_for(@resident) do |f| %>
  <% if @resident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resident.errors.count, "error") %> prohibited this resident from being saved:</h2>

      <ul>
      <% @resident.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :pin %><br />
    <%= f.text_field :pin %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/residents/edit.html.erb
<h1>Editing resident</h1>

<%= render 'form' %>

<%= link_to 'Show', @resident %> |
<%= link_to 'Back', residents_path %>

app/views/residents/index.html.erb
<h1>Listing residents</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Pin</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @residents.each do |resident| %>
  <tr>
    <td><%= resident.first_name %></td>
    <td><%= resident.last_name %></td>
    <td><%= resident.pin %></td>
    <td><%= resident.status %></td>
    <td><%= link_to 'Show', resident %></td>
    <td><%= link_to 'Edit', edit_resident_path(resident) %></td>
    <td><%= link_to 'Destroy', resident, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resident', new_resident_path %>

app/views/residents/new.html.erb
<h1>New resident</h1>

<%= render 'form' %>

<%= link_to 'Back', residents_path %>

app/views/residents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @resident.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @resident.last_name %>
</p>

<p>
  <b>Pin:</b>
  <%= @resident.pin %>
</p>

<p>
  <b>Status:</b>
  <%= @resident.status %>
</p>


<%= link_to 'Edit', edit_resident_path(@resident) %> |
<%= link_to 'Back', residents_path %>